// Mock data for DeepHire

const JOBS = [
  {
    id: "job-7a14",
    title: "Senior Full-Stack Engineer",
    team: "Platform · Infra",
    location: "Remote · US/EU",
    posted: "Apr 14, 2026",
    rubric: ["TypeScript", "Postgres", "Distributed systems", "Realtime infra", "On-call leadership"],
    seniority: "L5 — Senior",
    candidates: 14,
    verified: 9,
    flagged: 2,
    status: "Active",
  },
  {
    id: "job-3c91",
    title: "Founding ML Engineer",
    team: "Applied Research",
    location: "SF (hybrid)",
    posted: "May 02, 2026",
    rubric: ["PyTorch", "CUDA", "Eval infra", "LLM post-training"],
    seniority: "L6 — Staff",
    candidates: 8,
    verified: 3,
    flagged: 1,
    status: "Active",
  },
  {
    id: "job-12bf",
    title: "Developer Experience Lead",
    team: "Open Source",
    location: "Remote",
    posted: "Apr 03, 2026",
    rubric: ["Rust", "OSS maintenance", "Technical writing", "CLI/SDK design"],
    seniority: "L5 — Senior",
    candidates: 22,
    verified: 12,
    flagged: 3,
    status: "Active",
  },
  {
    id: "job-9ff2",
    title: "iOS Engineer, Performance",
    team: "Mobile",
    location: "NYC",
    posted: "Mar 28, 2026",
    rubric: ["Swift", "Instruments / profiling", "60fps UI", "Metal"],
    seniority: "L4 — Mid",
    candidates: 6,
    verified: 4,
    flagged: 0,
    status: "Paused",
  },
];

const CANDIDATES = [
  {
    id: "cand-amara",
    name: "Amara Okonkwo",
    handle: "amara-okonkwo",
    role: "Senior Full-Stack Engineer",
    jobId: "job-7a14",
    location: "Lisbon, PT",
    submitted: "2 hours ago",
    scores: { fit: 87, evidence: 92, shipped: 81, confidence: 78 },
    status: "Brief ready",
    avatar: "AO",
  },
  {
    id: "cand-quan",
    name: "Quan Vũ",
    handle: "quan-vu",
    role: "Senior Full-Stack Engineer",
    jobId: "job-7a14",
    location: "Berlin, DE",
    submitted: "Yesterday",
    scores: { fit: 74, evidence: 68, shipped: 82, confidence: 64 },
    status: "Brief ready",
    avatar: "QV",
  },
  {
    id: "cand-jess",
    name: "Jessamine Rhee",
    handle: "jess-rhee",
    role: "Senior Full-Stack Engineer",
    jobId: "job-7a14",
    location: "Toronto, CA",
    submitted: "Today, 09:12",
    scores: { fit: 0, evidence: 0, shipped: 0, confidence: 0 },
    status: "Analyzing",
    avatar: "JR",
  },
  {
    id: "cand-lior",
    name: "Lior Hartman",
    handle: "lior-h",
    role: "Founding ML Engineer",
    jobId: "job-3c91",
    location: "Tel Aviv, IL",
    submitted: "3 days ago",
    scores: { fit: 91, evidence: 88, shipped: 94, confidence: 86 },
    status: "Brief ready",
    avatar: "LH",
  },
  {
    id: "cand-pria",
    name: "Pria Bhattacharya",
    handle: "pria-b",
    role: "Developer Experience Lead",
    jobId: "job-12bf",
    location: "Bangalore, IN",
    submitted: "5 days ago",
    scores: { fit: 69, evidence: 72, shipped: 58, confidence: 60 },
    status: "Flagged",
    avatar: "PB",
  },
];

// Flagship candidate brief — Amara
const BRIEF = {
  id: "cand-amara",
  name: "Amara Okonkwo",
  handle: "amara-okonkwo",
  pronouns: "she / her",
  role: "Senior Full-Stack Engineer",
  jobId: "job-7a14",
  location: "Lisbon, Portugal · UTC+0",
  submitted: "Apr 22, 2026",
  brief: "Apr 22, 2026 · 18:42 UTC",
  links: {
    github: "github.com/amara-okonkwo",
    portfolio: "amara.codes",
    linkedin: "linkedin.com/in/amara-okonkwo",
    resume: "okonkwo_resume_2026.pdf",
  },
  scores: {
    fit: { value: 87, delta: +4, of: 100, label: "Fit Score", desc: "Match against role rubric" },
    evidence: { value: 92, delta: +6, of: 100, label: "Evidence", desc: "Strength of public support" },
    shipped: { value: 81, delta: -2, of: 100, label: "Shipped Work", desc: "Production-grade output" },
    confidence: { value: 78, delta: +1, of: 100, label: "Confidence", desc: "Overall signal coherence" },
  },
  oneLiner: "Distributed-systems engineer with strong, verifiable OSS footprint in Postgres tooling and Elixir realtime infra. Two production launches at scale; one timeline question to follow up on.",
  shipped: [
    {
      id: "ship-1",
      title: "pg-rewind-live",
      kind: "Open-source · 4.2k ★",
      blurb: "A streaming logical-replication tool for zero-downtime Postgres major-version upgrades. Maintains primary authorship and shipped 11 of last 14 releases.",
      whyImpressive: "Solves a real operational pain point with a careful, well-tested implementation. RFC-style proposal accepted into Postgres TODO list.",
      relevance: "Directly maps to the role's 'realtime infra' and 'Postgres at scale' must-haves.",
      stack: ["Rust", "Postgres WAL", "tokio", "protobuf"],
      links: [
        { kind: "repo", label: "github.com/amara-okonkwo/pg-rewind-live" },
        { kind: "demo", label: "pg-rewind.dev" },
        { kind: "writeup", label: "Engineering blog (3,400 words)" },
      ],
      metrics: [
        { k: "Stars", v: "4,218" },
        { k: "Contributors", v: "47" },
        { k: "Last commit", v: "3 days ago" },
        { k: "Tests", v: "94% cov." },
      ],
    },
    {
      id: "ship-2",
      title: "Sundial Realtime",
      kind: "Employer project · 2022–2024",
      blurb: "Led the v3 rewrite of an Elixir + Phoenix presence layer serving 2.1M peak concurrent connections across 6 regions. Drove p99 from 480ms → 92ms.",
      whyImpressive: "Public conference talk (ElixirConf EU '24) with reproducible benchmarks and a follow-up RFC adopted into Phoenix.Channel.",
      relevance: "Realtime infra leadership and on-call ownership — both explicit must-haves.",
      stack: ["Elixir", "Phoenix", "BEAM", "Kafka", "OpenTelemetry"],
      links: [
        { kind: "talk", label: "ElixirConf EU 2024 — 28 min" },
        { kind: "writeup", label: "Sundial engineering postmortem" },
      ],
      metrics: [
        { k: "Peak CCU", v: "2.1M" },
        { k: "p99 latency", v: "92ms" },
        { k: "Regions", v: "6" },
        { k: "Talk views", v: "34k" },
      ],
    },
    {
      id: "ship-3",
      title: "stream-keeper",
      kind: "Side project · 720 ★",
      blurb: "A small, beautifully-documented CLI for replaying Postgres WAL into test fixtures. Used by 11 companies (per public testimonials).",
      whyImpressive: "Strong documentation discipline and a thoughtful CLI surface. Several engineers cite it in interview prep posts.",
      relevance: "Demonstrates a clear product instinct for developer tools.",
      stack: ["Go", "Cobra", "Postgres"],
      links: [
        { kind: "repo", label: "github.com/amara-okonkwo/stream-keeper" },
        { kind: "demo", label: "Asciinema demo (3 min)" },
      ],
      metrics: [
        { k: "Stars", v: "720" },
        { k: "Releases", v: "v0.1 → v1.4" },
        { k: "Docs", v: "12 pages" },
      ],
    },
  ],
  verifiedClaims: [
    {
      id: "v1",
      claim: "Authored pg-rewind-live with 4.2k+ GitHub stars",
      source: "GitHub API · 11 sources",
      strength: 0.97,
      evidenceCount: 6,
    },
    {
      id: "v2",
      claim: "Led realtime infra at Sundial (2022–2024)",
      source: "Conference talk · LinkedIn · Crunchbase",
      strength: 0.91,
      evidenceCount: 5,
    },
    {
      id: "v3",
      claim: "Spoke at ElixirConf EU 2024",
      source: "Sched.com · YouTube · slides.com",
      strength: 0.99,
      evidenceCount: 4,
    },
    {
      id: "v4",
      claim: "Driving p99 latency from 480ms to 92ms",
      source: "Talk slides 14–22 · written postmortem",
      strength: 0.84,
      evidenceCount: 3,
    },
    {
      id: "v5",
      claim: "Contributed to Phoenix.Channel core",
      source: "GitHub PR #6182 · merged",
      strength: 0.94,
      evidenceCount: 2,
    },
  ],
  weakClaims: [
    {
      id: "w1",
      claim: "“Built a CUDA-accelerated retrieval pipeline at Sundial”",
      issue: "No public artifact. Not mentioned in talk, postmortem, or any commit footprint we can attribute.",
      severity: "ask-in-interview",
    },
    {
      id: "w2",
      claim: "“Managed a team of 6 engineers”",
      issue: "LinkedIn says 6; one ex-colleague's public org chart shows 3 direct reports. Worth clarifying.",
      severity: "minor",
    },
    {
      id: "w3",
      claim: "“5+ years TypeScript in production”",
      issue: "GitHub history shows TS commits only from late 2022. Resume claim may include side-project time.",
      severity: "minor",
    },
  ],
  risks: [
    {
      id: "r1",
      severity: "danger",
      title: "Timeline mismatch — Sundial vs. Northwind overlap",
      body: "Resume lists Sundial as Mar 2022 – Feb 2024, but LinkedIn shows Northwind through Apr 2022. Five-week unexplained overlap. Confirm whether contract or transition period.",
    },
    {
      id: "r2",
      severity: "warn",
      title: "Unsupported production claim — CUDA retrieval pipeline",
      body: "No commits, conference slides, or postmortem reference. We could not find any public artifact backing this resume bullet.",
    },
  ],
};

const EVIDENCE = {
  v1: {
    title: "Authored pg-rewind-live with 4.2k+ GitHub stars",
    strength: 0.97,
    pages: [
      { url: "github.com/amara-okonkwo/pg-rewind-live", note: "Repo. 4,218 stars. Top contributor (61% commits)." },
      { url: "github.com/amara-okonkwo/pg-rewind-live/graphs/contributors", note: "Contributor graph." },
      { url: "amara.codes/projects/pg-rewind-live", note: "Personal portfolio listing." },
      { url: "news.ycombinator.com/item?id=39281047", note: "Front-paged. 312 points. Author confirmed in thread." },
      { url: "postgresql.org/list/pgsql-hackers/2025-02/msg00214.html", note: "RFC discussion on hackers list." },
    ],
    snippets: [
      { src: "GitHub README", text: "“Maintained primarily by Amara Okonkwo (@amara-okonkwo). Shipped v0.9 — v1.4 between Aug 2024 and Apr 2026.”" },
      { src: "HN thread", text: "“I'm the author — happy to answer questions. The WAL-replay trick was the unlock; details in the design doc.”" },
      { src: "pgsql-hackers", text: "“The TODO entry now references Amara's proposal as the reference design.” — committer reply" },
    ],
    screenshot: "GitHub repo header (Playwright capture)",
  },
  v2: {
    title: "Led realtime infra at Sundial (2022–2024)",
    strength: 0.91,
    pages: [
      { url: "sundial.io/team (archive.org snapshot, Jan 2024)", note: "Listed as 'Staff Engineer, Realtime'." },
      { url: "linkedin.com/in/amara-okonkwo", note: "Self-reported tenure: Mar 2022 – Feb 2024." },
      { url: "crunchbase.com/organization/sundial", note: "Lists Amara as engineering lead in 2024 funding announcement." },
      { url: "youtube.com/watch?v=elixirconf-eu-24-aok", note: "ElixirConf talk: 'Realtime at Sundial'." },
    ],
    snippets: [
      { src: "Conference bio", text: "“Amara leads the realtime infra team at Sundial, where she rebuilt the presence layer to handle 2M+ concurrent connections.”" },
      { src: "TechCrunch Series B coverage", text: "“led by realtime infrastructure lead Amara Okonkwo.”" },
    ],
    screenshot: "ElixirConf talk page (Playwright capture)",
  },
};

window.JOBS = JOBS;
window.CANDIDATES = CANDIDATES;
window.BRIEF = BRIEF;
window.EVIDENCE = EVIDENCE;
